version: '3.1'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config:/prometheus
      - ./data/prometheus:/data
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    ports:
      - 9090:9090
    restart: always

  node:
    image: prom/node-exporter
    ports:
      - 9100:9100
    restart: always


  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./config:/prometheus
      - ./data/alertmanager:/data
    command:
      - '--config.file=/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093


  cadvisor:
    image: google/cadvisor
    ports:
      - 9880:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro


  alerta:
    image: varlite/alerta-web:latest
    # volumes:
      # - $PWD/config/config.json:/web/config.json
      # - C:\Users\mchambers\git\alerta-contrib\plugins\normalise:/tmp/normalise
      # - C:\Users\mchambers\Desktop\alerta-temp\files\prometheus.py:/usr/local/lib/python3.8/site-packages/alerta/webhooks/prometheus.py
    ports:
      - 8081:8080
      - 8082:2222
    depends_on:
      - db
    environment:
      # - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      - ADMIN_PASSWORD=super-secret # default is "alerta"
      - ADMIN_KEY=demo-key  # assigned to first user in ADMIN_USERS
      # - ADMIN_KEY_MAXAGE=500
      # - PLUGINS=normalise
    restart: always

  db:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
